### ISSUE TITLE
A filter to ignore certain things?

### ISSUE THREAD

**Issue by xrishox** [ercanserteli/video-condenser#2]
I'm running into a problem where the condensed audio is adding in stuff like birds chirping and music playing. A lot of the sound effects and stuff are contained within parenthesis and the music has musical notes.
![image](https://user-images.githubusercontent.com/23132250/132105802-894c97c5-f146-4f14-ade7-92c1d3da7ce6.png)
![image](https://user-images.githubusercontent.com/23132250/132106094-50760bb9-5f0a-41f8-814e-5cdf736f9d5e.png)

i think being able to filter out certain things from condenser would be a pretty nice feature. this can run into issues where parenthesis lines indicating speaker would be blocked, but it could probably be configured to only remove it if the entire line is in parenthesis or something.

![image](https://user-images.githubusercontent.com/23132250/132105989-550ea54b-9d60-4c53-b352-4222b55249a2.png)

**Comment by Geniusssmit** [comment]
I would like to see this option too!

**Comment by TehDaichi** [comment]
This would be awesome

**Comment by ercanserteli** [comment]
Added in d270ee5 with the new version v1.3.0
