### ISSUE TITLE
Can't choose external subs if video file has embedded subs?

### ISSUE THREAD

**Issue by TehDaichi** [ercanserteli/video-condenser#4]
If a video file has multiple embedded subs, but I want external subs to be used to target the audio, the "multiple subs detected" popup seems to only list the embedded subs, is it possible to fix this?

**Comment by ercanserteli** [comment]
Normally if you have external subs, even if you set the config "ask_when_multiple_srt" to true, it should still automatically use the external file without asking (assumes you always want the external file). It seems this doesn't work as it should if you run it on a folder, asks you to select an internal subtitle. Thanks for the report.

**Comment by TehDaichi** [comment]
No problem! Do you happen to have a rough ETA on when it'll be fixed?

**Comment by ercanserteli** [comment]
Hopefully fixed in d270ee5 with the new version v1.3.0

**Comment by TehDaichi** [comment]
Nice, I'll check it out and report in

**Comment by TehDaichi** [comment]
Yep, seems to be working properly, nice!
