### ISSUE TITLE
External folder

### ISSUE THREAD

**Issue by Geniusssmit** [ercanserteli/video-condenser#5]
Is it possible to condense single files to external folder instead of folder where file exists?

**Comment by Geniusssmit** [comment]
thank you very much for implementing this! Will you upload an update soon? btw I noticed 1 thing I can recommend adding to config.json by default 
```
  "filtered_characters": "♩♪♫♬～〜",
```
this second "〜" character is a different one, and I encountered it a few time in some subtitles. So it would be nice if you add as a default.

**Comment by ercanserteli** [comment]
Yes, I will release an update soon, and thanks for the recommendation I will add it to the default config

**Comment by ercanserteli** [comment]
v1.5.0 is released!

**Comment by Geniusssmit** [comment]
cool new features, but unfortunately it's not working for me at all, even with default settings :(
![image](https://github.com/ercanserteli/video-condenser/assets/24941285/8286dbac-62ec-4bd5-b49f-3ea4f352edb7)

**Comment by Geniusssmit** [comment]
Sorry I mean setting "fixed_output_dir": "E:\Condensed_Audio", 
crashes it

**Comment by ercanserteli** [comment]
I think it's because in json \ character is used for escape sequences, so you need to write either `"E:\\Condensed_Audio"` or `"E:/Condensed_Audio"`

**Comment by Geniusssmit** [comment]
yes, that helped, thanks
