### ISSUE TITLE
Program closes when start the processing

### ISSUE THREAD

**Issue by ghost** [ercanserteli/video-condenser#6]
Hello, thank you for the program but I'm running into problems:

here is the log:

2022-05-24 11:38:56 - C:\Users\Leonardo\Desktop\Leonardo\[Moozzi2] Shirokuma Cafe - TV + SP\[Moozzi2] Shirokuma Cafe - 01 (BD 1920x1080 x.264 Flac).mkv
-------------------------------------------------------------------------------------------------------------------------------------------------------
string index out of range
Traceback:
Traceback (most recent call last):
  File "condenser.py", line 355, in main
  File "condenser.py", line 209, in condense
  File "condenser.py", line 75, in extract_periods
  File "condenser.py", line 58, in filter_text
IndexError: string index out of range

can you please help me? thank you in advance!

**Comment by ercanserteli** [comment]
Could you please send me the subtitle that you get this problem with? If the sub is embedded in the video file, you can send me the whole video, or extract the sub using a program.

**Comment by ghost** [comment]
ofc, sorry the delay.

https://easyupload.io/pje6me

**Comment by ercanserteli** [comment]
Thanks, this problem should be fixed now in the new version (with commit [e791fd0](https://github.com/ercanserteli/video-condenser/commit/e791fd003204891ae00d3a59abb9e7134963af99)). Could you try downloading the v1.3.1 release and try with that?

**Comment by ghost** [comment]
Worked like a charm! thank you for your quick reply and fixes.. :)
