### ISSUE TITLE
work with only audio and sub files

### ISSUE THREAD

**Issue by ShinIchiHimura** [ercanserteli/video-condenser#8]
Hello ! thanks for the software , there is a possibility to add a feature that doesnt need the video as input ? like only audio and sub?
best regards

**Comment by ercanserteli** [comment]
Hi, this already worked with mp3 files but now in v1.4.0 the program recognizes most other audio formats as well. Keep in mind that you need to place external subtitles in the same name next to the input files, just like with videos.
